### ISSUE TITLE
Env variables left in cache causes gcc-11 builds on ubuntu to fail

### ISSUE THREAD

**Issue by marques-bruno** [cpp-best-practices/gui_starter_template#222]
Hey!
I freshly forked your template on my github account, but the initial commit doesn't pass the CI checks for ubuntu with gcc-11.

It seems that  some cached env variables are resurfacing during the "Configure CMake" step of the workflow, causing gcc to try to use clang includes, thus causing compile errors because of non-existent preprocessor defs (like `__has_include()`)

"7_Configure CMake.txt" logs:
```2022-05-12T15:26:59.9540894Z`   LLVM_PATH: /opt/hostedtoolcache/llvm/13.0.0/x64```
```2022-05-12T15:26:59.9541186Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/llvm/13.0.0/x64/lib:```
```2022-05-12T15:26:59.9541494Z   DYLD_LIBRARY_PATH: /opt/hostedtoolcache/llvm/13.0.0/x64/lib:```
```2022-05-12T15:26:59.9541805Z   CPATH: /opt/hostedtoolcache/llvm/13.0.0/x64/lib/clang/13.0.0/include```
```2022-05-12T15:26:59.9542101Z   LDFLAGS: -L/opt/hostedtoolcache/llvm/13.0.0/x64/lib```
```2022-05-12T15:26:59.9542388Z   CPPFLAGS: -I/opt/hostedtoolcache/llvm/13.0.0/x64/include```
```2022-05-12T15:26:59.9542677Z   LIBRARY_PATH: /opt/hostedtoolcache/llvm/13.0.0/x64/lib```

Sadly that's as far as my (non-existing) github actions skills could take me and I couldn't find what sets those environment variables...
CI compiles fine with llvm though, when removed from the exclusion list.

Thanks a lot for your templates, they are amazing!

**Comment by SK83RJOSH** [comment]
Having the same issue after forking this project. Causing half the test runs to fail and me a lot of misery. I hate to ping you directly, @lefticus but any chance this could be investigated?

**Comment by SK83RJOSH** [comment]
A very nasty fix for this is to override the environment variables. Change your `.github/workflows/ci.yml` build step to this and it should resolve compilation issues related to using incorrect headers:
```yml
      - name: Build
        # Clear out LLVM environment to avoid issues with GCC.
        env:
          LLVM_PATH: ""
          LD_LIBRARY_PATH: ""
          DYLD_LIBRARY_PATH: ""
          LDFLAGS: ""
          CPPFLAGS: ""
          LIBRARY_PATH: ""
          CPATH: ""
        # Execute the build. You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build ./build --config ${{matrix.build_type}}
```

I didn't notice any regression with LLVM builds, so these environment variables are generally not required it seems. These appear to be introduced by setup-cpp when installing LLVM. So this may be something that @aminya might want to look at. I imagine it should be easy enough to clear these after the install on unix within setup-cpp itself.
